version: '3'

services:
  database:
    image: mongo
    ports: 
      - "27017:27017"
    networks:
      - webnet
  funquiz:
    image: vgarapani/funquiz_server
    ports:
      - "80:4000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - webnet

networks:
  webnet: