version: '3'

services:
  app:
    build: ./
    image: funquiz
    expose:
      - 80
    environment:
      NODE_ENV: production
      SERVER_PORT: 80
      MONGO_HOST: mongodb://database/funquiz
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
